version: "3.7"
services:
  frontend:
    build: frontend/.
    ports:
      - 4321:4321
    network_mode: "host"
  backend:
    build: backend/.
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
